### ISSUE TITLE
datums.realizationMethod codelist

### ISSUE THREAD

**Issue by RogerLott** [ISO-TC211/ISO19111#10]
In the Datums package we have a new codelist called RealizationMethod. This is used only by an attribute in the VerticalReferenceFrame class. But the geodetic concept of realization is more general than just applying to vertical. I therefore suggest that we change the name of this codelist (and the datatype for VerticalReferenceFrame.realization) from RealizationMethod to VerticalRealization.

**Comment by jetgeo** [comment]
OK, done. 
![datum](https://cloud.githubusercontent.com/assets/7501876/25317919/2f9883fc-2883-11e7-90b7-902958e715be.png)

**Comment by jetgeo** [comment]
Change attribute to method and codelist to VerticalMethod

**Comment by jetgeo** [comment]
OK, done.

![datum](https://user-images.githubusercontent.com/7501876/27140082-f39fbaf8-5124-11e7-846b-33c5b61d86e2.png)

**Comment by jetgeo** [comment]
Changed back to realizationMethod and RealizationMethod based on mail discussion
