### ISSUE TITLE
ImageDatum/CRS and EngineeringDatum/CRS

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19111#12]
From @RogerLott (2017-05-17):
A rather pedantic issue. The definition of imageDatum is "engineering datum which defines the relationship of a coordinate system to an image". This implies that ImageDatum should be subtyped off EngineeringDatum. But the UML does not follow this, ImageDatum is currently subtyped off Datum. We have discussed this minor anomaly and think the image datum definition is fine, and to make the 19111 document more consistent the UML should follow this. So although this change has absolutely no impact on model inheritance and implementation, we ask that:

- [x] (i) ImageDatum should be subtyped off EngineeringDatum rather than Datum.

- [x] (ii) ImageCRS  be subtyped off EngineeringCRS rather than SingleCRS (we think this is a logical extension of (i).

Although these two changes to the model are trivial, the changes impact several of the diagrams.

**Comment by jetgeo** [comment]
Ok, done. New figures in https://github.com/ISO-TC211/ISO19111/tree/master/Figures/Main%20version.

**Comment by jetgeo** [comment]
Revert. The definition will be changed instead.

**Comment by RogerLott** [comment]
PT decided to resolve ambiguity between model and text by reverting to Image CRS/ImageDatum being sutyped directly off singleCRS/Datum and changing text to conform to this.

**Comment by jetgeo** [comment]
OK, done.

**Comment by jetgeo** [comment]
Done for Datum too.
