### ISSUE TITLE
Associations between CoordinateOperation and Data Epoch

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19111#13]
From @RogerLott (2017-05-17):
Another minor issue. For the associations between CoordinateOperation and Data Epoch, we wonder whether we can find some more meaningful names for either the associations or role names. These are operations on coordinates to change the epoch. Epoch = time. So source and target are not intuitively connected with time. **startEpoch** and **finishEpoch**, or **beginEpoch** and **endEpoch**, intuitively would  be more relevant to 'time'. 
We would be grateful  if you can suggest some improvement to the current names of either these associations or their role names (whichever is most appropriate from a modelling perspective).

**Comment by jetgeo** [comment]
I am not really sure that I agree here. 
If the purpose of the operations is to change epoch for coordinates from one given epoch to another, "Source" and "Target" sounds more intuitive to me. "Start" and "finish" or "begin" and "end" sounds more like we have a time period starting from start/begin and ending at "finish/end"?

**Comment by RogerLott** [comment]
In a dynamic CRS a point on the surface of the earth is moving. We are NOT changing epoch. We are changing COORDINATE VALUES for the moving point over a user-defined _period_ between two epochs.  SourceEpoch and TargetEpoch or SourceTime and TargetTime do not feel correct. What about PeriodStart and PeriodEnd? 19108 TMPeriodDuration expects an 8601 string for PeriodDuration, epochs are expressed as decimal years. So IntervalStart and IntervalEnd?

**Comment by mcraymer** [comment]
[Checking if my email reply will work. Or maybe I have to log into GitHub to reply?]

I don't like the terms "start" & "end" in describing the epochs. That might be interpreted as the very start and very end of the movement with no movement before and after those times. Of course most crustal movements have lasted and will last for millennia long before and after the typical epochs that will be used.

Perhaps the simpler terms "from" & "to" epochs would be a better description for this kind of thing; i.e, the epochs for the "from" and "to" positions of the point. So we would have "FromTime" and "ToTime" for the positions of the point. I don't think there would be any misinterpretation of those terms.

-Mike

**Comment by mcraymer** [comment]
Or "FromEpoch" and "ToEpoch" or "FromDate" and "ToDate". I forgot to mention I also don't like the term "period". I think it makes things unnecessarily more complex and is not as intuitive as the simple "from" and "to".
