### ISSUE TITLE
Extent description

### ISSUE THREAD

**Issue by RogerLott** [ISO-TC211/ISO19111#15]
The diagram "Identified Object with data types from ISO19115" is missing the description attribute from the EX_Extent class, but is included in the constraint. The diagram does show all of the *element role names against the associations so only description is missing from the formula in the constraint. As this is an important attribute for CRS usage I suggest it should be included in the diagram. (Having said that, a counter-argument is that the attributes for the associated classes from Extent do not show their attributes).

**Comment by jetgeo** [comment]
Agree. New version uploaded.
