### ISSUE TITLE
Axis Direction codeslist

### ISSUE THREAD

**Issue by RogerLott** [ISO-TC211/ISO19111#21]
Add the following axis direction attributes from 19162 to the 19111 AxisDirection class:
(all Conditional, cardinallity 1)

**UML identifier**          **Description**
- [x]  forward                    Axis positive direction is forward; for an observer at the centre of the object this is will be towards its front, bow or nose.
- [x] aft	                       Axis positive direction is aft; for an observer at the centre of the object this will be towards its back, stern or tail.
- [x] port	                       Axis positive direction is port; for an observer at the centre of the object this will be towards its left.
- [x] starboard	               Axis positive direction is starboard; for an observer at the centre of the object this will be towards its right.
- [x] clockwise	               Axis positive direction is clockwise from a specified direction.
- [x] counterClockwise    Axis positive direction is counter clockwise from a specified direction.
- [x] towards	               Axis positive direction is towards the object.
- [x] awayFrom  	       Axis positive direction is away from the object.
- [x] unspecified              Axis positive direction is unspecified.

**Comment by jetgeo** [comment]
Ok. Done. The new values are added at the bottom of the code list. Is the sorting ok?
![coordinate systems](https://user-images.githubusercontent.com/7501876/27171413-b6298d10-51b1-11e7-8b95-29635849569a.png)

**Comment by RogerLott** [comment]
There are natural groups in this list that I feel should be kept together, e.g. all of the compass directions, all of the column/row/displays, etc. On those grounds there is no case for an alphabetical sort. The only minor improvement I could suggest is to keep all of the spatial directions together so move future and past to between awayFrom and unspecified. This is not very important. Just as, perhaps more, useful would be sorting the CS subtypes alphabetically (affine, Cartesian, cylindrical, ellipsoidal, linear and parametric down the left column; polar, spherical, temporal, userDefined and vertical down the right column. And that is not very important either. All just aesthetics.  I leave it to you whether you feel it worth your time impriving the aesthetics. As far as I am concerned this can be closed as it is now.

**Comment by jetgeo** [comment]
It is possible to group the values by using stereotypes "compassDirections", "grid", etc. This has no practical consequences, it would be just for perception. But I leave it to you to decide whether it's worth it.
