### ISSUE TITLE
Navigability for Datum-CRS

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19111#22]
I think the Datum-CRS associations must be navigable both ways, because of the ellipsoid constraint. We may have discussed this earlier?

![datum](https://user-images.githubusercontent.com/7501876/27152909-c5bd82e8-514f-11e7-9813-649b7c81035a.png)
![datum crs associations](https://user-images.githubusercontent.com/7501876/27152911-c896eed2-514f-11e7-9369-3bc8b066d202.png)

**Comment by RogerLott** [comment]
I don't recall any discussion on this but seems logical to allow the constraint re ellipsoid on GeodeticReferenceframe to work. I don't see any backward compatibility issues.
