### ISSUE TITLE
Calendar optional

### ISSUE THREAD

**Issue by marqh** [ISO-TC211/ISO19111#25]
The aim of this ticket is to propose a comment to the 19111 editing committee raising this issue for discussion.

To provide less verbose syntax, such as for WKT-CRS, and to provide
backwards compatibility with ISO19162 WKT-CRS v1.0 I propose that
Calendar is made optional within the 19111 model.

this would enable current examples in ISO19162 to continue to be used, e.g.

```
WKT-CRS vn1.0 12-063r5 
14.4 Example of WKT describing a temporal CRS

TIMECRS[“GPS Time”,
        TDATUM[“Time origin”,
        TIMEORIGIN[1980-01-01T00:00:00.0Z]],
    CS[temporal,1],AXIS[“time”,future],TIMEUNIT[“day”,86400.0]]


```

as well as fully defined examples using updated syntax, such as

```
TIMECRS["Calendar hours from 1979-12-29",
	TDATUM["1979-12-29",
        TIMEORIGIN[1979-12-29T00:00:00.0Z],CALENDAR[prolepticGregorian]],
    CS[temporal,1],AXIS["time",future],
        TIMEQUANTITY[count,"hour"]
        TIMECOUNT["hour"]
    ]

Example coordinate values
[48, 96, 144]

```

Alternatively, could standards such as ISO19162 define a default value
such that Calendar is optional within that encoding, but assumed to be
the default value if not provided explicitly in the encoding.  Would
this enable 19111 to remain unchanged?
(note: in 19111 is prime meridian is optional, and assumed to be Greenwich if undefined, see table 51)

What is the preferred approach for enabling `Calendar` to be optional with a default value in encodings such as WKT-CRS ISO19162

**Comment by marqh** [comment]
based on discussions with Roger, Martin and I, we suggest that calendar is continued to be mandatory in the UML and table 62
Additionally, a statement is requested to be added, similar to the statement in table 51 (prime meridian) detailing the default behaviour

```
NOTE The default value for calendar is 'prolepticGregorian'.
```

**Comment by jetgeo** [comment]
The default value can be handled in the UML as well, as illustrated bellow.

![datum](https://user-images.githubusercontent.com/7501876/30518621-d979ab44-9b83-11e7-9c11-017a52b54d22.png)

**Comment by desruisseaux** [comment]
It is fine for me. I was not aware of this notation. I searched on internet and found [one on IBM site](https://www.ibm.com/developerworks/rational/library/content/RationalEdge/sep04/bell/index.html) (search "default") using the same syntax for the same purpose. So it seems the proper way to do.

**Comment by RogerLott** [comment]
This looks fine as means of dealing with the default calendar. I am closing the issue, but note that this version of the diagram is superseded by the change to the ellipsoid class covered in issue #31.
