### ISSUE TITLE
ImageCRS etc

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19111#28]
From the meeting in Southampton 2019-09-12:
Delete ImageCRS, DerivedIMageCRS and ImageDatum.

New figures (See also https://github.com/ISO-TC211/ISO19111/tree/master/Figures/Main%20version):
![coordinate reference systems](https://user-images.githubusercontent.com/7501876/30327949-2e02f29c-97ce-11e7-92f8-86f90fe7b1fb.png)

![derived crs](https://user-images.githubusercontent.com/7501876/30327953-32938ec0-97ce-11e7-9551-b31c9990204e.png)

![datum crs associations](https://user-images.githubusercontent.com/7501876/30327961-392fe332-97ce-11e7-83c8-c5870675cfd1.png)

![datum](https://user-images.githubusercontent.com/7501876/30327966-3fd1d7cc-97ce-11e7-9a25-4e3ab4df29a0.png)

**Comment by RogerLott** [comment]
- [x] The PixelInCell class should also be deleted. (Actually it should be moved to the 19123-1 model).

**Comment by RogerLott** [comment]
I am not sure about the ExtendedCS class. The purpose of the OrdinalCS class was to have the coordinateDataType as Integer. The model as created yesterday also allows it to be a characterstring or number. These are needed for TemporalCS but are they required for OrdinalCS?

**Comment by marqh** [comment]
> I am not sure about the ExtendedCS class. The purpose of the OrdinalCS class was to have the coordinateDataType as Integer. The model as created yesterday also allows it to be a characterstring or number. These are needed for TemporalCS but are they required for OrdinalCS?

see https://github.com/ISO-TC211/ISO19111/issues/24#issuecomment-329442261 supporting the removal of the ExtendedCS class

**Comment by jetgeo** [comment]
Ok, PixelInCell is removed.

 I am closing this issue and continuing the discussion on Temporal/Ordinal etc on #24.
