### ISSUE TITLE
Triaxial ellipsoid

### ISSUE THREAD

**Issue by RogerLott** [ISO-TC211/ISO19111#31]
The planetry science communirty have expressed a need for the model to support a triaxial ellipsoid. This could be done without any backward compatibility issues by adding to the Ellipsoid class (in the Datums package) one further optional attribute:
+semi-median axis: Length [0..1]

This would also be consistent with the triaxial ellipsoid extension documented in ISO 19162 annex D.

**Comment by jetgeo** [comment]
Se below 

![datum](https://user-images.githubusercontent.com/7501876/30521357-9bf24c8c-9bbe-11e7-8f20-ace0f819a460.png)

**Comment by RogerLott** [comment]
That looks fine. I will close the issue.
