### ISSUE TITLE
Amend class and attribute names

### ISSUE THREAD

**Issue by RogerLott** [ISO-TC211/ISO19111#33]
To accord with comments made on the 19111 CD ballot, please make te following changes:
- [x] 1. In Datums::DynamicGeodeticReferenceFrame, change attribute name from +referenceEpoch to +frameReferenceEpoch. 
- [x] 2. In Datums::DynamicVerticalReferenceFrame, change attribute name from +referenceEpoch to +frameReferenceEpoch. 
- [x] 3. Change Datums::Ensemble class name to Datums::DatumEnsemble. This will impact the count constraints in Coordinate Reference Systems::SingleCRS and in Coordinate Reference Systems::DerivedCRS.
- [x] 4. In Coordinate Operations::OperationMethod, delete the attributes +sourceDimensions and +targetDimensions.

**Comment by jetgeo** [comment]
OK, done. 
Also: changed role name from "ensemble" to "datumEnsemble".
Ref. also ppt attached to comment from @RogerLott in #19 .
See new figures in https://github.com/ISO-TC211/ISO19111/tree/master/Figures
