### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by RogerLott** [ISO-TC211/ISO19111#38]
This may be a stupid question (if so attribute it to jet lag) but in the diagram
![fig 2 internal package suppliers](https://user-images.githubusercontent.com/27864408/33860959-1d1225d8-ded3-11e7-9e8a-2c55f9b09fb0.png)
do we have the direction of dependency of coordinates correct? Should the arrow heads be at the CRS and CoordinateOperations end rather than at the Coordinates end?

**Comment by jetgeo** [comment]
The arrows shall point from the package that use another package to the package it uses. But I must admit I haven't thougth through which package uses what. Probably, almost all packages uses other packages in this model.

**Comment by jetgeo** [comment]
I believe this version is correct. 
![internal package suppliers](https://user-images.githubusercontent.com/7501876/33880779-00c10f10-df33-11e7-99ef-3df5c5ee0890.png)

**Comment by RogerLott** [comment]
OK
