### ISSUE TITLE
Attributes in ObjectUsage class in CRS package diagram

### ISSUE THREAD

**Issue by RogerLott** [ISO-TC211/ISO19111#42]
Jetgeo, there is inconsistency in the diagram for the CRS package compared to the diagrams for the Datums package and the CoordinateOperations package. In the CRS package the domain attribute is shown. For consistency the ObjectUsage.domain attribute should be removed from the CRS package diagram.

(An alternative approach would be to include the attributes in the IdentifiedObject and ObjectUsage classes where these classes appear in the CRS, CS, Datum and CoordinateOperation package diagrams. This would have some advantage to 19111 readers in that all attributes for the packages are on the diagram, but may make the diagrams too cluttered).

Please provide revised png and wmf files.

**Comment by jetgeo** [comment]
Good observation. I have uploaded a new version of the CRS diagram now.
