### ISSUE TITLE
Changes following DIS ballot

### ISSUE THREAD

**Issue by RogerLott** [ISO-TC211/ISO19111#43]
@jetgeo 
The following changes are required to accommodate editorial comments made in the 19111 DIS ballot.

1. In the UML for the Coordinates package, delete the second constraint "{crs.oclAsType(GeodeticCRS VerticalCRS) and count(crs.velocityModel)>0 implies count(coordinateEpoch)=1}" from both of the CoordinateMetadata and Geometry classes.

2. In the Coordinate Reference Systems package:
(i) change the definition of the GeodeticCRS class to "A coordinate reference system associated with a geodetic reference frame and a three-dimensional Cartesian or spherical coordinate system. If the geodetic reference frame is dynamic then the geodetic CRS is dynamic, else it is static." (i.e. delete "or if the geodetic CRS has an association to a velocity model ")
ii) change the definition of the GeographicCRS class to "A coordinate reference system associated with a geodetic reference frame and a two- or three-dimensional ellipsoidal coordinate system. If the geodetic reference frame is dynamic then the geographic CRS is dynamic, else it is static." (i.e. delete "or if the geographic CRS has an association to a velocity model " and correct "geodetic" to "geographic").
iii) change the definition of the VerticalCRS class to "A coordinate reference system having a vertical reference frame and a one-dimensional vertical coordinate system used for recording gravity-related heights or depths. Vertical CRSs make use of the direction of gravity to define the concept of height or depth, but the relationship with gravity may not be straightforward. If the vertical reference frame is dynamic then the vertical CRS is dynamic, else it is static. " (i.e. delete "or if the vertical CRS has an association to a velocity model " and insert "vertical" before the last occurrence of CRS).

Grateful if you could provide both .png and .wmf versions of updated diagrams. Thanks.

**Comment by jetgeo** [comment]
Working on it...
Just cheking: So the requirement on Geometry and CoordinateMetadata to have a coordinateEpoch if the type of CRS is Geodetic og Vertical, and it has a velocityModel, is no longer valid?
Been a while since I worked on this model, so I don't remeber the details...
![relation to geometry](https://user-images.githubusercontent.com/7501876/42451043-645c5a78-8386-11e8-9271-36726583b50e.png)

**Comment by jetgeo** [comment]
Done, new figures uploaded.

**Comment by RogerLott** [comment]
@jetgeo said
"Just cheking: So the requirement on Geometry and CoordinateMetadata to have a coordinateEpoch if the type of CRS is Geodetic og Vertical, and it has a velocityModel, is no longer valid?"
The velocity model bit is removed, but if the CRS has a dynamic reference frame then coordinateEpoch is required. The diagram is as required, thanks.
