### ISSUE TITLE
19111 diagrams minor changes

### ISSUE THREAD

**Issue by RogerLott** [ISO-TC211/ISO19111#44]
@jetgeo grateful if you could make minor changes to two of the diagrams:
1. The Operations part 1 diagram is inconsistent in showing the non-navigable roles at the CoordinateOperation end of the two associations to Data Epoch. These should be removed from the diagram (to be consistent with the associations to CRS).

2. In the 19111 document the Operations with Data Epoch diagram at full resolution causes a note to be pushed onto the next page. To stop this I have reduced the size of the diagram, but this makes the text smaller than is usual in an ISO document (see attached). Could you reformat this diagram to make it less extensive in height (up-down direction), please. One possibility for doing this is to make the box for the CRS class in particular, but also for the Data Epoch class, less tall by removing unnecessary white space. See attached. However other solutions such as putting the DataEpoch and CRS classes at the same level (both below Coordinate Operation) might be preferable.

Thanks.
![19111 is page 21](https://user-images.githubusercontent.com/27864408/43148339-9a2f27d2-8f54-11e8-90b6-937ea2979079.jpg)

**Comment by jetgeo** [comment]
Ok, done.
