### ISSUE TITLE
Changed modelling of Derived CRSs

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19111#7]
Extracted from #6 - Just the part with DerivedCRS
**(Separate branch for discussion)**

The objective is to simplify the modelling of derived CRSs by removing the derivedCRS class and allowing derivedCRSs to either inherit their baseCRSs datum (or datum.ensemble) or to have their own datum. For vertical CRSs the possibility of their reference frame being levelling, geoid or tidal based remains.

A.	CRS Package

- [x] Remove the aggregation from DerivedCRS to Conversion and replace it with one from SingleCRS to Conversion. 

- [x] Delete the association currently from DerivedCRS to SingleCRS and replace it with a recursive association on SingleCRS. I think it would be best if this association be named – does DerivedCRS seem ok?

- [x] If we are naming the recursive association above, then we should also add the name DerivedCRS to the association from ProjectedCRS to GeodeticCRS

- [x] Change the subtyping of ProjectedCRS to be off SingleCRS

- [x] Remove the DerivedCRS class

**Question: There are constraints in the derivedCRS class. Are they still needed and if so where do they go?**

**Comment by jetgeo** [comment]
Ok, done (I think). Probably have to do some cleaning in the diagrams. 
The constraints from DerivedCRS has been moved to SingleCRS, for discussion. 
New diagrams in https://github.com/ISO-TC211/ISO19111/tree/master/Figures/Alternative%20version%20DerivedCRS

**Comment by jetgeo** [comment]
Forgott this: 

- [ ] For a derived CRS the two new associations from SingleCRS (named derivedCRS and Definition) are both required: is there any way of linking them together in UML? (Constraint on SingleCRS {count(baseCRS+conversion)=0 or count(baseCRS+conversion)=2 implies singleCRS is derived} ??)

**Comment by RogerLott** [comment]
- [ ] On the Operations part 1 diagram the label "Definition" should be on the association from SingleCRS to Conversion, not on the verticalCRS subtype.

**Comment by jetgeo** [comment]
Closing this, based on the conclusions from the meeting 2017-05-03.
