### ISSUE TITLE
Removal of the distinction between conversion and transformation

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19111#8]
Extracted from #6 - just the part with the distinction between conversion and transformation
**(Separate branch for discussion)**
The objective is to simplify coordinate operations through the removal of the distinction between conversion and transformation.

- [ ] Remove the aggregation currently from DerivedCRS to Conversion and replace it with one from DerivedCRS to SingleOperation. 

- [ ] Move the aggregation (named HeightTransformation after (2) above) currently from VerticalCRS to Conversion to be from VerticalCRS to SingleOperation.

- [ ] Delete the Conversion and Transformation classes

**Comment by jetgeo** [comment]
OK, figures in https://github.com/ISO-TC211/ISO19111/tree/master/Figures/Alternative%20version%20Transformation

**Comment by RogerLott** [comment]
SingleOperation class will need to be changed from Abstract to Concrete.

**Comment by jetgeo** [comment]
From @RogerLott:
Then there is a question regarding the role names for the associations from DerivedCRS to SingleOperation (currently +conversion) and from VerticalCRS to SingleOperation (currently +transformation). With the removal of the Conversion and Transformation classes are these role names still appropriate? My personal inclination is to leave them as they are, as it might help in the textual description of the implicit/explicit inclusion of source and target CRS in operation descriptions. But is that appropriate?

**Comment by jetgeo** [comment]
Think this is done now. 
![operations part 1](https://cloud.githubusercontent.com/assets/7501876/25770600/9fb2f400-3239-11e7-9543-49ae4fcf670e.png)

**Comment by jetgeo** [comment]
What about the constraint on CoordinateOperation, refering to Conversion?

**Comment by jetgeo** [comment]
Revert...

**Comment by RogerLott** [comment]
PT agreed that this constraint was required and the way to enforce it was be re-instating Conversion and Transformation classes.

**Comment by jetgeo** [comment]
OK. Done.

**Comment by RogerLott** [comment]
After reverting, SingleOperation needs to be changed back to Abstract (italic font).

**Comment by jetgeo** [comment]
Ok, done.
