### ISSUE TITLE
datums.Ensemble missing attribute

### ISSUE THREAD

**Issue by RogerLott** [ISO-TC211/ISO19111#9]
In the Datums package when the datums.Ensemble class was first proposed (at that time in the CRS package) it had a mandatory attribute +ensembleInaccuracy:Measure which seems to have disappeared. I don't recall it having been deliberately removed so I suspect it has been accidentally dropped. It is an estimate of the positional differences in the ensemble of realizations. I think it should be reinstated. However this attribute is very similar to the coordinateOperationAccuracy attribute in the CoordinateOperation class which has a datatype of DQ_PositionalAccuracy, so I wonder whether the datatype for ensembleInaccuracy should also be DQ_PositionalAccuracy. Also whether the attribute name might be best as ensembleAccuracy?

**Comment by jetgeo** [comment]
I don't remember ever creating this attribute, so I guess I must have forgotten it somehow. Good example of the advantage of handling single issues on Github. 
I have added it now as ensembleAccuracy with datatype DQ_PositionalAccuracy and multiplicity 1..1, as suggested. I believe "...Accuracy" is a better term then "...Inaccuracy", according to the terminology in 19157. 
![datum](https://cloud.githubusercontent.com/assets/7501876/25317884/5bd14dba-2882-11e7-9ad8-a75d232caee6.png)
